name: debugging_dartserver_with_flutter_webapp
description: Web server sandbox
version: 0.0.1
author: Brandon Donnelson

dependencies:
   mime_type: 0.3.1

# https://dart.dev/tools/pub/dependencies#dependency-overrides
dependency_overrides:
  # package dependencies so a specific VM doesn't have to be built
  mime_type:
    path: ./packages/pub.dartlang.org/mime_type-0.3.1
  